spring:
    datasource:
        url: jdbc:mysql://49.232.218.20:3306/offershow?characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: Caowenjia12
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
    configuration:
        jdbc-type-for-null: 'null'
        map-underscore-to-camel-case: true
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.bjtu.offer_app.entity
